# Generated by Django 5.2.5 on 2025-09-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_enrollment_date_enrolled_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='formative_assessment',
            field=models.FileField(blank=True, null=True, upload_to='module_assessments/formative/'),
        ),
        migrations.AddField(
            model_name='module',
            name='summative_assessment',
            field=models.FileField(blank=True, null=True, upload_to='module_assessments/summative/'),
        ),
    ]
